---
- name: Install curl
  apt:
    name: curl
    state: present
    update_cache: yes

- name: Install K3s
  shell: |
    curl -sfL https://get.k3s.io | sh -s - \
      --kube-apiserver-arg="oidc-ca-file=/home/vagrant/rootCA.crt" \
      --kube-apiserver-arg=oidc-groups-claim="groups" \
      --kube-apiserver-arg=oidc-issuer-url=https://192.168.56.11:8443/realms/kubernetes \
      --kube-apiserver-arg=oidc-client-id=bologna1 \
      --kube-apiserver-arg=oidc-username-claim=sub \
      --bind-address=0.0.0.0
  args:
    creates: /usr/local/bin/k3s

- name: Fix kubeconfig permissions
  file:
    path: /etc/rancher/k3s/k3s.yaml
    mode: '0644'

- name: Install Helm
  shell: |
    curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
    chmod 700 get_helm.sh
    ./get_helm.sh
  args:
    creates: /usr/local/bin/helm

- name: Install Crossplane
  shell: |
    kubectl create namespace crossplane-system || true
    helm repo add crossplane-stable https://charts.crossplane.io/stable
    helm repo update
    helm install crossplane --namespace crossplane-system crossplane-stable/crossplane
  args:
    creates: /var/lib/rancher/k3s/server/manifests/crossplane.yaml

- name: Apply experiment CRDs
  command: kubectl apply -f /home/vagrant/deployments/experiment-provider/crds

- name: Apply provider-kubernetes
  command: kubectl apply -f /home/vagrant/deployments/kubernetes-provider/provider-kubernetes.yaml

- name: Configure provider-kubernetes
  shell: |
    SA=$(kubectl -n crossplane-system get sa -o name | grep provider-kubernetes | sed -e 's|serviceaccount/|crossplane-system:|g')
    kubectl create clusterrolebinding provider-kubernetes-admin-binding --clusterrole cluster-admin --serviceaccount="${SA}"
    kubectl apply -f /home/vagrant/deployments/kubernetes-provider/config-in-cluster.yaml

- name: Apply XRDS definitions
  command: kubectl apply -f /home/vagrant/deployments/compositeResources/xdrs/

- name: Apply XRDS compositions
  command: kubectl apply -f /home/vagrant/deployments/compositeResources/compositions/

- name: Deploy CouchDB sync operator
  command: kubectl apply -f /home/vagrant/deployments/couchDBsyncoperator/deploy.yaml

- name: Install experiment provider
  command: kubectl apply -f /home/vagrant/deployments/experiment-provider/experiment-provider.yaml

- name: Apply experiment provider config
  command: kubectl apply -f /home/vagrant/deployments/experiment-provider/experiment-provider-config.yaml

- name: Apply remote resource configs
  shell: |
    kubectl apply -f /home/vagrant/deployments/kubernetes-provider/remoteResourceXDR.yaml
    kubectl apply -f /home/vagrant/deployments/kubernetes-provider/providerconfigXRD.yaml
    kubectl apply -f /home/vagrant/deployments/kubernetes-provider/providerconfigComposition.yaml
    kubectl apply -f /home/vagrant/deployments/kubernetes-provider/remoteResourceComposition.yaml
