---
- name: Install dependencies
  apt:
    name: [curl, docker.io]
    state: present
    update_cache: yes

- name: Add vagrant user to docker group
  user:
    name: vagrant
    groups: docker
    append: yes

- name: Pull Docker images
  command: docker pull {{ item }}
  with_items:
    - couchdb:3.4.2
    - quay.io/keycloak/keycloak:26.0.7

- name: Run Keycloak
  command: >
    docker run -d --name keycloak -p 8443:8443
    -e KC_BOOTSTRAP_ADMIN_USERNAME=admin
    -e KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    -v /home/vagrant/import:/opt/keycloak/data/import
    -v /home/vagrant/cert:/cert
    quay.io/keycloak/keycloak:latest start
    --https-certificate-file=/cert/cert.pem
    --https-certificate-key-file=/cert/key.pem
    --hostname-strict=false --import-realm --verbose
  args:
    creates: /var/lib/docker/containers/keycloak

- name: Run CouchDB
  command: >
    docker run -d -p 5984:5984 --name couchdb
    -e COUCHDB_USER=admin
    -e COUCHDB_PASSWORD=password
    couchdb:latest
  args:
    creates: /var/lib/docker/containers/couchdb

- name: Wait for CouchDB
  wait_for:
    host: 127.0.0.1
    port: 5984
    delay: 20
    timeout: 60

- name: Create experiments database
  uri:
    url: http://127.0.0.1:5984/experiments
    method: PUT
    user: admin
    password: password
    force_basic_auth: yes
    status_code: 201,202,412

- name: Insert experiment1 doc
  uri:
    url: http://127.0.0.1:5984/experiments/experiment1
    method: PUT
    user: admin
    password: password
    force_basic_auth: yes
    body_format: json
    body:
      ExperimentName: "exp1a"
      ExperimentGroup: "experiment1"
      EndTime: "1/1/1"
      SiteID: "bologna1"
      ResourceKind: "xslicenamespaces.experiment.mmwunibo.it"
      ResourceObject:
        virtualMemory: "4Gb"
        virtualCpu: "2"
        experimentGroup: "experiment1"
    status_code: 201,202,409
